### ISSUE TITLE
lost-column throws errors

### ISSUE THREAD

**Issue by subpixelch** [corysimmons/lost#103]
$sudo gulp default

Error Output:
```
[16:42:23] Starting 'css'...
{ name: 'TypeError',
  message: 'Object 0 has no method \'indexOf\'',
  stack: 'TypeError: Object 0 has no method \'indexOf\'\n    at /srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:330:41\n    at /srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:121:34\n    at /srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:106:26\n    at Rule.each (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:91:22)\n    at Rule.eachInside (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:105:21)\n    at /srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:109:32\n    at Root.each (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:91:22)\n    at Root.eachInside (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:105:21)\n    at Root.eachDecl (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:119:25)\n    at Root.replaceValues (/srv/users/serverpilot/apps/knecht/public/node_modules/postcss/lib/container.js:328:14)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss' }
[16:42:23] Finished 'css' after 47 ms
```

my gulpfile:

```Javascript
var gulp = require('gulp'),
    postcss = require('gulp-postcss'),
    sourcemaps = require('gulp-sourcemaps'),
    minifyCss = require('gulp-minify-css'),
    concat = require('gulp-concat'),
    imagemin = require('gulp-imagemin'),
    changed = require('gulp-changed'),
    jshint = require('gulp-jshint'),
    notify = require('gulp-notify'),
    plumber = require('gulp-plumber'),
    stripDebug = require('gulp-strip-debug'),
    uglify = require('gulp-uglify'),
    lost = require('lost'),
    browserSync = require('browser-sync').create(),
    autoprefixer = require('autoprefixer-core'),
    reload = browserSync.reload,
    mixins = require('postcss-mixins'),
    atImport = require('postcss-import'),
    selector = require('postcss-custom-selectors'),
    size = require('postcss-size'),
    nested = require('postcss-nested'),
    simple = require('postcss-simple-vars'),
    colorFunction = require('postcss-color-function'),
    easing = require('postcss-easings'),
    fontVariant = require('postcss-font-variant'),
    postcssColorGray = require('postcss-color-gray'),
    minmax = require('postcss-media-minmax'),
    customMedia = require('postcss-custom-media'),
    colorHexAlpha = require('postcss-color-hex-alpha'),
    mqpacker = require('css-mqpacker'),
    subpixel = require('postcss-banner'),
    postfocus = require('postcss-focus'),
    customProperties = require('postcss-custom-properties'),
    calc = require('postcss-calc')

var onError = function(err) {
    console.log(err);
}


// Static Server + watching scss/html files
gulp.task('serve', ['css', 'images', 'jshint', 'scripts', 'fonts'], function() {
    browserSync.init({
        server: "./www",
        port: 9000,
        ghostMode: {
            clicks: true,
            location: true,
            forms: true,
            scroll: true
        },
        notify: false,
        open: false
    });
    gulp.watch("./src/css/**/*", ['css']);
    gulp.watch("./src/js/**/*", ['jshint', 'scripts']);
    gulp.watch("./src/img/**/*", ['images']);
    gulp.watch("./src/fonts/**/*", ['fonts']);
    gulp.watch("./www/**").on('change', reload);
});



// Copy fonts from a module outside of our project (like Bower)

gulp.task('fonts', function() {
    return gulp.src(['./src/fonts/**/*'], {
            read: false
        })
        .pipe(gulp.dest('./www/fonts'));
});

// Compress and minify images to reduce their file size

gulp.task('images', function() {
    return gulp.src('./src/img/**')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(changed('./www/img'))
        .pipe(imagemin())
        .pipe(gulp.dest('./www/img'))
        .pipe(notify({
            message: 'Images task complete'
        }));
});


// Hint all of our custom developed Javascript to make sure things are clean

gulp.task('jshint', function() {
    return gulp.src('./src/js/**/*.js')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(jshint())
        .pipe(jshint.reporter('default'))
        .pipe(notify({
            message: 'JS Hinting task complete'
        }));
});


// Combine/Minify/Clean Javascript files
gulp.task('scripts', function() {
    return gulp.src(['./src/js/plugins.js', './src/js/main.js', './src/js/vendor/**/*.js'])
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(concat('scripts.js'))
        .pipe(stripDebug())
        .pipe(uglify())
        .pipe(gulp.dest('./www/js/'))
        .pipe(notify({
            message: 'Scripts task complete'
        }));
});


gulp.task('css', function() {
    var processors = [
        mixins(),
        simple(),
        atImport(),
        nested,
        customProperties({
            preserve: false
        }),
        customMedia(),
        minmax(),
        selector(),
        lost(),
        fontVariant(),
        colorHexAlpha(),
        postcssColorGray(),
        colorFunction(),
        size,
        easing(),
        postfocus(),
        calc({
            precision: 2
        }),
        mqpacker(),
        autoprefixer({
            browsers: ['last 1 version']
        }),
        subpixel({
            banner: '!  █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ♥ ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█\n' +
                '     ▒     subpixel GmbH Rheinfelden    ▒\n' +
                '     ░         www.subpixel.ch          ░\n' +
                '     ▒       welcome@subpixel.ch        ▒\n' +
                '     █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n' +
                ''
        })
    ];
    return gulp.src('./src/css/style.css')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(sourcemaps.init())
        .pipe(postcss(processors))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./www/css'))
        .pipe(reload({
            stream: true,
            notify: false
        }));
});

gulp.task('default', ['serve']);
```

## This is my CSS
```CSS
header {
    lost-center: 1200px 30px;
}
.logo{
  lost-column: 2/6;
}
```

All column-functions throw out the same error. 
Without "lost-column: 2/6" it works fine as well
All other lost functions work just fine...

Any ideas?

**Comment by corysimmons** [comment]
> All column-functions throw out the same error. 
Without "lost-column: 2/6" it works fine as well

So `lost-column` is throwing the error or `lost-center`?

**Comment by subpixelch** [comment]
no, just the *-columns functions

**Comment by corysimmons** [comment]
What do you mean exactly `*-columns functions`? I'm not getting an error when I try to run your CSS.

**Comment by subpixelch** [comment]
When I use lost-columns: 1/2 I get those errors... could it be that my node setup is broken? I tried it on two different Systems an had the same error...Did you try It with my gulpfile?

**Comment by corysimmons** [comment]
Use `lost-column` not `lost-columns`

**Comment by subpixelch** [comment]
I rewrote the gulpfile. Now everything runs smooth again. Sorry about the confusion. - Please close. Thanks a lot!

**Comment by corysimmons** [comment]
No problem. Glad it's fixed. =)

**Comment by Dfmarulanda** [comment]
i got "undefined is not a function" when im trying to use
 ``` css
lost-column
```
Gulpfile.js{
 ``` javascript
//Vars
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var lost = require('lost');
var cssnano = require('cssnano');
var cssvariables = require('postcss-css-variables');
var cssnext = require('cssnext');
var cssgrace = require('cssgrace');
var csswring = require('csswring');
var debug = require('gulp-debug');
var fontVariant = require("postcss-font-variant");


//Watch task
gulp.task("watch", function() {
  gulp.watch("./css/*.css", ["styles"])

});



//Styling task
gulp.task('styles', function () {
    return gulp.src('./css/*.css')
        .pipe(postcss([cssnext,cssgrace,csswring,lost(),cssvariables,cssnano,fontVariant]))
        .on('error', function(err){ console.log(err.message); })
        .pipe(gulp.dest('../Ghost/content/themes/eternity/assets/css/'));
});


//Default task
gulp.task("default", ["watch"])

``` 


}

**Comment by corysimmons** [comment]
@Dfmarulanda Can you try it without all the other PostCSS plugins?

**Comment by Dfmarulanda** [comment]
I did it before reopen the issue.

**Comment by corysimmons** [comment]
Are you sure `gulp-postcss` is installed? Can I see your `package.json`?

**Comment by Dfmarulanda** [comment]
Lost functions like lost-center works.
Im using fine the other postcss plugins.

Package.JSON

```javascript
{
  "name": "Eternity",
  "description": "Write what u want",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^3.0.0",
    "grunt-contrib-concat": "*",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-hub": "*",
    "grunt-postcss": "^0.4.0",
    "gulp": "^3.8.11",
    "gulp-debug": "^2.0.1",
    "load-grunt-tasks": "*",
    "postcss-css-variables": "^0.3.1"
  }
}
```

**Comment by corysimmons** [comment]
To be honest, I'm not sure.

@ai Any ideas?

**Comment by ai** [comment]
@Dfmarulanda we need a full stacktrace. What is text after error name?
